
name: create _ssl_tls_svc_profile
label: 4. Create an SSL/TLS Service profile - xml

description: Create an SSL/TLS Service profile using just created server certificate

extends:

type: panos

labels:
  collection:
    - X509 Certificates

variables:
  - name: ssl_tls_service_profile
    description: SSL TLS Service Profile to be used for captive portal
    default: cp-ssl-tls-service-profile
    type_hint: text

snippets:
    - name: ssl_tls_profile
      xpath: /config/shared/ssl-tls-service-profile
      file: 0-ssl-tls-profile.xml
