
name: create _ssl_tls_svc_profile
label: 1. Create an SSL/TLS Service profile

description: Create an SSL/TLS Service profile using just created certificates
dependency:

type: panos

labels:
  collection:
    - X509 Certificates

variables:
  - name: ssl_tls_service_profile
    description: Gateway-1 and Portal-1 - SSL TLS Service Profile
    default: ssl_tls_service_profile
    type_hint: text
snippets:
    - name: ssl_tls_profile
      xpath: /config/shared/ssl-tls-service-profile
      file: 0-ssl_tls_profile.xml
